# Generated by Django 4.2.3 on 2023-10-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_remove_event_created_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='question_images'),
        ),
    ]
