# Generated by Django 4.2.3 on 2023-10-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_alter_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
