# Generated by Django 4.2.3 on 2023-10-25 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0020_questionimage_remove_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionimage',
            name='user',
            field=models.ForeignKey(default='ethan', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
